runtime: custom
env: flex
service: prerender

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^node_modules/(.*/)?

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

manual_scaling:
  instances: 1

health_check:
  enable_health_check: False
